//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pantti.rc
//
#define IDKUITTI                        3
#define IDSALDO_OK                      3
#define IDD_ABOUTBOX                    100
#define IDD_PANTTI_FORM                 101
#define IDR_PANTTI                      102
#define IDR_MAINFRAME                   128
#define IDR_PANTTITYPE                  129
#define IDS_PANTTIKUITTI                129
#define IDD_ENSIM_LNR                   130
#define IDS_PKTEXT1                     130
#define IDD_DLG_ENSIM_LNR               130
#define IDD_DLG_UUSI_LAINA              131
#define IDS_PKTEXT2                     131
#define IDD_DLG_LUNASTUS                132
#define IDS_PANTTINUMERO                132
#define IDD_DLG_UUDISTUS                133
#define IDS_PKTEXT3                     133
#define IDD_DLG_VAKMUUTOS               134
#define IDS_PKTEXT4                     134
#define IDD_DLG_ASETUS                  135
#define IDS_PKTEXT5                     135
#define IDS_PKTEXT6                     136
#define IDS_PKTEXT7                     137
#define IDD_DLG_TAPAHTUMA               137
#define IDS_PKTEXT8                     138
#define IDD_DLG_ARVIOMIES               138
#define IDS_LAINASUMMA                  139
#define IDD_DLG_LOGIN                   139
#define IDS_PVM                         140
#define IDD_DLG_KASSA                   140
#define IDS_PKERAPVM                    141
#define IDD_DLG_TUOTE                   141
#define IDS_KORKO_KK                    142
#define IDD_DLG_KASSATARKASTUS          142
#define IDS_KORKO_KK_YKS                143
#define IDD_DLG_KASSARA                 144
#define IDD_DLG_KASSARAPORTTI           144
#define IDS_MK                          145
#define IDD_DLG_AUCTION                 145
#define IDS_KORKOMK_KK                  146
#define IDD_DLG_HKRAPORTTI              146
#define IDS_SHV_MAKSUT                  147
#define IDS_SHV_MAKSYT_YKS              148
#define IDD_DLG_YJ_MAKSU                148
#define IDS_PANKKIIN1                   149
#define IDD_DLG_AJ_KUITTAUS             149
#define IDS_VIITE                       150
#define IDD_DLG_YJ_KUITTAUS             150
#define IDS_VAKUUTAN_OIK1               151
#define IDD_DLG_HALTIJAN_MUUTOS         151
#define IDS_VAKUUTAN_PAIKKAPAIV         152
#define IDD_DLG_LAINAKULUT              152
#define IDS_ALLEKIRJ_X                  153
#define IDS_ALLEKIRJ_JA                 154
#define IDI_CAYOTE                      154
#define IDS_LUNASTAJATXT1               155
#define IDI_BUGS                        155
#define IDS_LIITTEETTXT                 156
#define IDS_LUNASTAJATXT2               157
#define IDI_BUNNY                       157
#define IDS_LUNASTAJATXT3               158
#define IDI_rabbit2                     158
#define IDS_VAKUUTAN_OIK2               159
#define IDS_ERAPVM_HUOM                 160
#define IDI_RABBIT_RUNNING              160
#define IDS_PANKKIIN2                   161
#define IDI_WHISTLE                     161
#define IDS_M_LAJAN_PAATT               162
#define IDI_HOURCLASS                   162
#define IDS_KORKO                       163
#define IDI_HAMMER                      163
#define IDS_KUITTIMAKSU                 164
#define IDI_PKNIFE                      164
#define IDS_UUDISTUS                    165
#define IDI_TOOLS                       165
#define IDS_LUNASTUS                    166
#define IDD_DLG_KASSALOKI               166
#define IDS_LYHENNYS                    167
#define IDD_DLG_HAKULISTA               167
#define IDS_YHTEENSA                    168
#define IDD_DLG_YJTILITYS               168
#define IDS_TOD_VUOSIKORKO              169
#define IDS_KORKO_V_YKS                 170
#define IDS_KUITTI_SUOR_LAMAKSUISTA     171
#define IDS_LAINANUMERO                 172
#define IDS_PAAOMA                      173
#define IDS_KUITIN_KATOAMINEN           174
#define IDS_MUISTUTUSKIRJE              175
#define IDS_VAKUUKSIEN_VARMISTUS        176
#define IDS_POSTITUSKULUT               177
#define IDS_PANTTITODISTUS              178
#define IDS_MUUT_KULUT                  179
#define IDS_VIIVA                       180
#define IDS_YLIM_SMAKSU                 181
#define IDS_VAKUUTAN_OIK3               182
#define IDS_EURO                        183
#define IDS_ALENNUS                     184
#define IDC_CUSTOM_GRIDLAINAT           1000
#define IDC_HTUN                        1001
#define IDC_SNIMI                       1002
#define IDC_ETSI                        1003
#define IDC_CUSTOM_GRID_LAINARIVIT      1004
#define IDC_ETSI_LAINA                  1005
#define IDC_KATUOS                      1007
#define IDC_PTP                         1008
#define IDC_VARMENNUS                   1012
#define IDC_HUOM                        1013
#define IDC_LAINANRO                    1014
#define IDC_HUOM2                       1014
#define IDC_UUSI_LAINA                  1015
#define IDC_KUITTI                      1016
#define IDC_ENSLAINANNR                 1017
#define IDC_LUNASTUS                    1018
#define IDC_UUDISTUS                    1019
#define IDC_VAKMUUTOS                   1020
#define IDC_HLOTUNNUS                   1021
#define IDC_PVM                         1022
#define IDC_LAINA_AIKA                  1023
#define IDC_TOIMISTO                    1024
#define IDC_ERAPV                       1025
#define IDC_SAILVAKMAKSU                1026
#define IDC_KUITTIMAKSU                 1027
#define IDC_ODOTUSPVM                   1028
#define IDC_YLIMSAILMAKSU               1029
#define IDC_LIITTEET                    1030
#define IDC_NIMI                        1031
#define IDC_MUISTUTUSMAKSU1             1031
#define IDC_SEURAAVA_LYHENNYS           1031
#define IDC_SEURAAVA_LYHENNYS2          1032
#define IDC_EIMUISTUTUSTA               1033
#define IDC_SEURHKPV                    1034
#define IDC_YLIMSAILMAKSU2              1034
#define IDC_YLIMSAILMAKSU3              1035
#define IDC_MK                          1037
#define IDC_EURO                        1038
#define IDC_KURSSI                      1039
#define IDC_LAINANNIMI                  1040
#define IDC_UUDEN_LAINAN_RIVIT          1041
#define IDC_VAKUUSARVO                  1042
#define IDC_LAINASUMMA                  1043
#define IDC_BTN_LASKE                   1044
#define IDC_KORKOKUUKAUSIA              1044
#define IDC_KORKO_YHT_2                 1044
#define IDC_KUUKAUSIKORKO               1045
#define IDC_VAKUUSARVO2                 1045
#define IDC_SUORITUSJONO                1046
#define IDC_KUUKAUSIKORKO_YHT           1046
#define IDC_LAINASUMMA4                 1046
#define IDC_SUORITUSJONON_SUMMA         1047
#define IDC_YLITYSAIKA_PV               1047
#define IDC_CLEAR_SJONO                 1048
#define IDC_LAINASUMMA3                 1048
#define IDC_KORKOPR                     1049
#define IDC_REMOVE_SJONORIVI            1049
#define IDC_LNR                         1050
#define IDC_KORKO1                      1051
#define IDC_PAIVAKORKO                  1051
#define IDC_RAJA1                       1052
#define IDC_VIIVASTYSKORKO_YHT          1052
#define IDC_SHV_PAIVAKORKO              1052
#define IDC_KORKO2                      1053
#define IDC_KORKO_YHT                   1053
#define IDC_RAJA2                       1054
#define IDC_LAINASUMMA2                 1054
#define IDC_BTN_LASKE2                  1054
#define IDC_LAJAN_SHVKORKO_YHT          1054
#define IDC_KORKO3                      1055
#define IDC_LAINASUMMAN_MUUTOS          1055
#define IDC_SHVYHTEENSA                 1055
#define IDC_SHV_MAKSUT_YHT              1055
#define IDC_RAJA3                       1056
#define IDC_LAJAN_SHVKORKO_YHT2         1056
#define IDC_KORKO4                      1057
#define IDC_SHVYHTEENSA2                1057
#define IDC_KORKOPAIVIA                 1058
#define IDC_LUNASTUSPAIVA               1059
#define IDC_KORKOPAIVIA_LAINA_AJALLA    1059
#define IDC_KORKO_YHT2                  1060
#define IDC_YLIMSAILMAKSUPERKK          1060
#define IDC_MAKSETTAVA_YHT              1061
#define IDC_KORKOPAIVIA_LAINA_AJAN_YLI  1062
#define IDC_UUDISTUSPAIVA               1063
#define IDC_KORKOKK_LAINA_AJAN_YLI      1064
#define IDC_LAINAN_LYHENNYKSET          1065
#define IDC_MUUTOS_LAINARIVIT           1066
#define IDC_KKKORKO_LAINA_AJAN_YLI      1066
#define IDC_KKKORKO_YHT_LAINA_AJAN_YLI  1067
#define IDC_KKKORKO_LAINA_AJAN_YLI2     1067
#define IDC_KKKORKO_YHT_LAINA_AJAN_YLI2 1068
#define IDC_LAINAN_KOROTUS              1068
#define IDC_TYHJENNA                    1070
#define IDC_TALLENNA                    1071
#define IDC_KORJAA                      1072
#define IDC_BTEST                       1073
#define IDC_PUH                         1076
#define IDC_FAX                         1077
#define IDC_BUTTON1                     1078
#define IDC_LASKE                       1079
#define IDC_LAINAN_KIELTO               1080
#define IDC_TALLETA_LAINATIEDOT         1081
#define IDC_KUITIN_KATOAMINEN           1082
#define IDC_KATOAMISMAKSU               1083
#define IDC_MUISTUTUSMAKSU2             1084
#define IDC_MUISTUTUSKIRJEMAKSU1        1085
#define IDC_VAKUUSVARMENNUS             1085
#define IDC_MUISTUTUSKIRJEMAKSU2        1086
#define IDC_VAKUUSVARMENNUSMAKSU        1087
#define IDC_POSTITUSKULUT               1088
#define IDC_MUUT_KULUT                  1089
#define IDC_MAKSETTAVAYHT               1089
#define IDC_MUISTUTUSKIRJE1_PVM         1090
#define IDC_MUISTUTUSKIRJE2_PVM         1091
#define IDC_MUISTUTUSKIRJEMAKSU         1092
#define IDC_LAINAN_TAPAHTUMAT           1093
#define IDC_HUUTOKAUPPA                 1094
#define IDC_SP1                         1095
#define IDC_SP2                         1096
#define IDC_POSTITUS                    1099
#define IDC_SHV_MAKSUPR                 1102
#define IDC_SAILVAKMAKSU_PR             1103
#define IDC_SHV_PR                      1104
#define IDC_SHV_MK_KK                   1105
#define IDC_SHV_KORKOKK                 1106
#define IDC_SHV_MAKSU_YHT1              1107
#define IDC_SHV_MAKSU_YHT2              1108
#define IDC_NIMI_HTUN                   1111
#define IDC_MUIST_HUOM                  1112
#define IDC_LNRO_PV_EPV                 1113
#define IDC_VAPAAEHT_LYH                1115
#define IDC_SHVMAKSUT_YHT               1116
#define IDC_KOROTUS                     1116
#define IDC_HTUN_NIMI                   1120
#define IDC_PERU                        1121
#define IDC_KIELTO                      1122
#define IDC_ASIAKAS_LAINANR             1123
#define IDC_EVENTS                      1125
#define IDC_RUOTS_HTUN                  1127
#define IDC_HTUN2                       1128
#define IDC_ARVIOMIESRIVIT              1129
#define IDC_UUSI_ARVIOMIESRIVI          1130
#define IDC_USERID                      1132
#define IDC_EDIT1                       1133
#define IDC_PW                          1133
#define IDC_KASSALISTA                  1134
#define IDC_KORKOPRKK                   1134
#define IDC_LISAA_UUSI_KASSA            1135
#define IDC_SHVMAKSUKORKOPRKK           1135
#define IDC_KASSA                       1136
#define IDC_LAINAN_PV                   1136
#define IDC_POISTA_KASSA                1137
#define IDC_ARVIOMIES                   1137
#define IDC_LAINAN_ERAPV                1137
#define IDC_SIIRTOSUMMA                 1138
#define IDC_AIKA                        1138
#define IDC_LAINAN_LUNUUD_PV            1138
#define IDC_NOSTO                       1139
#define IDC_AIKA2                       1139
#define IDC_PANO                        1140
#define IDC_EDELLINENSALDO              1140
#define IDC_KASSA1                      1141
#define IDC_KASSA2                      1142
#define IDC_SIIRTO                      1143
#define IDC_RAHASIIRROT_KASSA           1144
#define IDC_VISASIIRTO                  1144
#define IDC_TALLETA                     1145
#define IDC_VISA                        1145
#define IDC_POISTA                      1146
#define IDC_TUOTELISTA2                 1148
#define IDC_PANKKIKORTTITOSITTEITA      1149
#define IDC_SALDOTOSITTEIDENMUKAAN      1150
#define IDC_YHT                         1151
#define IDC_KASSARAPORTTI               1152
#define IDC_GRID_KASSARAPORTTI          1153
#define IDC_EI_MUIST                    1155
#define IDC_RAP_PVM                     1156
#define IDC_PVKSTART                    1157
#define IDC_PVKSTOP                     1158
#define IDC_LAINAKANTA                  1159
#define IDC_PAIVAKIRJA                  1160
#define IDC_KP_RAPORTTI                 1161
#define IDC_PYORISTYS                   1166
#define IDC_MUISTKIRJERAJA_MK           1167
#define IDC_MUISTKIRJE1RAJA_PV          1168
#define IDC_MUISTKIRJE2RAJA_PV          1169
#define IDC_HK_ERAPV_RAJA               1170
#define IDC_TUOTERYHMAT                 1171
#define IDC_LAINAN_TUOTERYHMA           1172
#define IDC_VARASTO                     1173
#define IDC_HKMAKSU_PR                  1174
#define IDC_HK_POISTOMAKSU              1175
#define IDC_MY_VALM_MAKSU_PR            1176
#define IDC_MY_VALM_MAKSU_MIN           1177
#define IDC_ARVOPAP_VAL_MAKSU_PR        1178
#define IDC_HK_LAINA                    1179
#define IDC_HK_LAINARIVIT               1180
#define IDC_LAINANUMERO_LABEL           1181
#define IDC_PALAUTA_BTN                 1182
#define IDC_HKLISTA_BTN                 1183
#define IDC_KUVAUKSET_BTN               1184
#define IDC_STATIC_TXT_TALLETUS_IND     1185
#define IDC_OHJE                        1186
#define IDC_HUUTOKAUPPAN_VALINTA        1187
#define IDC_BTN_RAPORTTI                1188
#define IDC_LOANS_IN_AUCTION            1189
#define IDC_LOANS_IN_AUCTION_SUM        1190
#define IDC_INTERESTS_AND_EXPENSES      1191
#define IDC_AUCTION_EXPENSES            1192
#define IDC_AUCTION_BIDS                1193
#define IDC_BALANCE                     1194
#define IDC_DEFICIT                     1195
#define IDC_LOAN_PARTIALLY_SOLD_NUMBER  1196
#define IDC_PARTIALLY_SOLD_TOTAL_LOAN   1197
#define IDC_PARTIALLY_SOLD_SUM          1198
#define IDC_PAATOS                      1199
#define IDC_RAPORTTI                    1200
#define IDC_TILASTOTXT1                 1201
#define IDC_SOLDLOANS_AMOUNT            1201
#define IDC_TILASTOTXT2                 1202
#define IDC_SOLDLOANS_SUM               1202
#define IDC_LAINOJAYHT                  1203
#define IDC_TOIMENPIDEKIELTORAJA        1203
#define IDC_LAINANKIELTO                1204
#define IDC_TOIMENPIDEKIELTOPVM         1205
#define IDC_YLIJAAMAN_ILMOITUSMAKSU     1207
#define IDC_YLIJAAMAN_TILITYSAIKA       1208
#define IDC_YLIJAAMAN_ALARAJA           1209
#define IDC_YJKIRJEEN_LAINAT            1210
#define IDC_KIRJENR                     1211
#define IDC_HENKTUN                     1212
#define IDC_SULJE                       1213
#define IDC_VALITTU_LAINA               1214
#define IDC_CUSTID                      1216
#define IDC_CUSTNAME                    1217
#define IDC_PERSONID                    1218
#define IDC_PAYMENT                     1219
#define IDC_ACCEPT                      1220
#define IDC_YLIJ_TILITYSAIKA_ASTIED     1222
#define IDC_OLD_LOANS                   1224
#define IDC_LANR                        1226
#define IDC_ASNIMI                      1227
#define IDC_YLIJMK                      1228
#define IDC_HTUN1                       1228
#define IDC_MOVE                        1229
#define IDC_KOROT_JA_SHV_KULUT          1230
#define IDC_INTERESTGRID                1232
#define IDC_USERINFO                    1234
#define IDC_KORKO_KK                    1235
#define IDC_YLIMSAILMAKSUPERKUUKAUSI    1236
#define IDC_LUNASTETUTPANTIT            1237
#define IDC_EVENTROWS                   1240
#define IDC_DESKLOGROWS                 1241
#define IDC_HAE                         1243
#define IDC_LOPPSUMMA_EUROINA           1246
#define IDC_SHV_YHT2                    1247
#define IDC_ALENNUS                     1248
#define IDC_BTN_LAINAKANTA              1255
#define IDC_BTN_ETSI                    1258
#define IDC_KULUT_YHT                   1261
#define IDC_TEELAINA                    1262
#define IDC_HENK_TARK                   1263
#define IDC_OK                          1264
#define IDC_LUNASTA                     1265
#define IDC_CANCEL                      1266
#define IDC_UUDISTA                     1267
#define IDC_UUDISTUS_TAI_LUNASTUS       1268
#define IDC_KULUT_LUNYHT                1270
#define IDC_KULUT_UUDYHT                1271
#define IDC_SIIRTOSAATAVAT              1271
#define IDC_LOPPUSUMMA_MK               1272
#define IDC_MUISTUTUS1                  1272
#define IDC_LAHUOM                      1273
#define IDC_MUISTUTUS2                  1273
#define IDC_HL_INFO                     1274
#define IDC_INFO1                       1275
#define IDC_UNDO                        1276
#define CUSTOMERINFO                    1277
#define IDC_CUSTOMERINFO                1278
#define IDC_YJ                          1279
#define ID_LAINAT_UUSILAINA             32771
#define ID_LAINAT_LUNASTUS              32772
#define ID_LAINAT_UUDISTUS              32773
#define ID_LAINAT_VAKUUSMUUTOS          32774
#define ID_LAINAT_HALTIJANMUUTOS        32775
#define ID_LAINAT_LAINALUOTTOTAPPIOIHIN 32776
#define ID_LAINAT_LAINANMITTINTI        32777
#define ID_LAINAT_SIIRTOHUUTOKAUPPAAN   32778
#define ID_HALLINTA_TUOTTEET            32779
#define ID_HALLINTA_KASSAT              32780
#define ID_HALLINTA_ARVIOMIEHET         32781
#define ID_HALLINTA_ASIAKKAAT           32782
#define ID_HALLINTA_ASETUKSET           32783
#define ID_HALLINTA_LOPETUS             32784
#define ID_HALLINTA_KASSANSALDO         32785
#define ID_RAPORTIT_KASSAPIVKIRJA       32786
#define ID_RAPORTIT_MUISTUTUSKIRJEET    32787
#define ID_HUUTOKAUPPA_HAKULISTA        32788
#define ID_HUUTOKAUPPA_SIIRTOHUUTOKAUPPAAN 32789
#define ID_HUUTOKAUPPA_HUUTOKAUPPA      32790
#define ID_HUUTOKAUPPA_LAINANSIIRTOHUUTOKAUPPAAN 32791
#define ID_RAPORTIT_ODOTUSLISTA         32793
#define ID_HUUTOKAUPPA_YLIJMKIRJEET     32794
#define ID_HUUTOKAUPPA_YLIJMNKUITTAUSASIAKKAALLE 32795
#define ID_HUUTOKAUPPA_YLIJMNKUITTLAINAAMOLLE 32796
#define ID_HUUTOKAUPPA_VAPAAEHTALIJPERIMINENASIAKKAALTA 32797
#define ID_ETSI_ETSIASIAKAS             32798
#define ID_ETSI_ETSILAINA               32799
#define ID_OHJE_TIETOJA                 32800
#define ID_ETSI_TYHJENNASIAKASTIED      32801
#define ID_ASIAKKAAT_TALLETAUUSIASIAKAS 32802
#define ID_ASIAKKAAT_TALLETAMUUTTUNEETASIAKASTIEDOT 32803
#define ID_LAINAT_LAINANKULUT           32804
#define ID_LAINAT_LAINANTAPAHTUMAT      32805
#define ID_LAINAT_TULOSTAKUITITSUORITJONONTAP 32806
#define ID_BUTTON32807                  32807
#define ID_BUTTON32808                  32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32811                  32811
#define ID_RAPORTIT_KASSALOKI           32812
#define ID_RAPORTIT_KIRJE1              32814
#define ID_RAPORTIT_KIRJE2              32815
#define ID_RAPORTIT_UUSIKUITTI          32816
#define ID_ASIAKKAAT_HENKTUNNUS         32817
#define ID_ASETUKSET_TYHJENNRUUTU       32818
#define ID_ASIAKKAAT_OSOITE             32819
#define ID_HUUTOKAUPPA_ALLEVUODENVANHATYLIJMT 32821
#define IDS_PANKKIIN3                   57346
#define IDS_PANKKIIN4                   57347

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1280
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
